pipeline{
    agent { node { label 'AGENT' } }
    // timeout{ time: 1, unit: 'minite'}
    parameters{
        string( name: 'Name', description: "Enter your name")
        choice( name: 'Environment', choices: ['Dev', 'PROD'], description: "Chose environment" )
    }
    stages{
        stage("Build"){
            when {
                expression{
                    params.choice.environment == 'Dev'
                }
            }
            steps{
                sh '''
                ls -l
                pwd
                echo "Building stage is success"
                '''
            }
        }
        stage("Test"){
            steps{
                sh '''
                echo "Testing stage is success"
                '''
            }
        }
        stage("Deploy"){
            steps{
                sh '''
                echo "Deploying stage is success"
                '''
            }
        }
    }
    post{
        always{
            echo 'I will always say Hello again!'
        }
    }
}